version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./fospublisher
    volumes:
      - /app/node_modules
      - ./fospublisher:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'

  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: app_backend
    volumes:
      - ./server:/app
